### ISSUE TITLE
menu.py: error interpreting this plugin

### ISSUE THREAD

**Issue by jasonhuang1115** [mb0rt/Nuke-NodeHelpers#1]
Hi, 
Thanks for sharing this Nuke tool. Trying to install the NodeHelpers but ran into this error below. The build I downloaded last night seemed to work just fine but it has an additional "vendor" folder it the zip.
Traceback (most recent call last):
  File "C:/Users/user/.nuke/NodeHelpers_mbort/menu.py", line 6, in <module>
    from mbort import backdrop_palette
  File "C:/Users/user/.nuke/NodeHelpers_mbort\mbort\backdrop_palette\__init__.py", line 1, in <module>
    from . import backdrop
  File "C:/Users/user/.nuke/NodeHelpers_mbort\mbort\backdrop_palette\backdrop.py", line 4, in <module>
    import backdrop_widget
  File "C:/Users/user/.nuke/NodeHelpers_mbort\mbort\backdrop_palette\backdrop_widget.py", line 219
    row = 0n
           ^
SyntaxError: invalid syntax

**Comment by mb0rt** [comment]
Thanks Jason for pointing this. I really appreciate. 
It was a typing issue( "row = 0" instead of "row = 0**n**", not sure how that "n" got there ¯\_(ツ)_/¯ ). 
Fixed.

**Comment by jasonhuang1115** [comment]
Thank you for fixing that. cheers!
